# Generated by Django 2.2 on 2019-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchfixtures',
            name='comments',
            field=models.TextField(),
        ),
    ]
