# Generated by Django 2.2 on 2019-04-11 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officials',
            name='email',
        ),
        migrations.RemoveField(
            model_name='officials',
            name='image',
        ),
        migrations.RemoveField(
            model_name='officials',
            name='name',
        ),
        migrations.RemoveField(
            model_name='officials',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='officials',
            name='uname',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='image',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='ref_name',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='uname',
        ),
        migrations.RemoveField(
            model_name='team',
            name='coach_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='team',
            name='uname',
        ),
        migrations.AddField(
            model_name='officials',
            name='official_user_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referee',
            name='ref_user_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='coach_user_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_image',
            field=models.ImageField(default=1, upload_to='teams/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officials',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='referee',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='images/%m/%d')),
                ('gender', models.CharField(max_length=10)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'ref'), (3, 'coach'), (4, 'official')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
