# Generated by Django 2.2 on 2019-04-12 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20190411_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach_user_name',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.ImageField(upload_to='teams'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_user_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='coach_user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Coach'),
            preserve_default=False,
        ),
    ]
