# Generated by Django 2.1.3 on 2019-05-26 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Officials')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='league.League')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Team')),
            ],
        ),
    ]
