# Generated by Django 2.2 on 2019-04-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('official_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Officials')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='league.League')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Team')),
            ],
        ),
    ]
