# Generated by Django 2.2.1 on 2019-05-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('venue', models.CharField(max_length=30)),
                ('comments', models.TextField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='league.League')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Referee')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team1', to='users.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team2', to='users.Team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField()),
                ('points', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='league.League')),
                ('match_fixture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='matches.MatchFixtures')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Referee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Team')),
            ],
        ),
    ]
