# Generated by Django 2.2 on 2019-04-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20190411_1854'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='birth_certificate',
            field=models.ImageField(upload_to='birth/%m/%d'),
        ),
        migrations.AlterField(
            model_name='players',
            name='photo',
            field=models.ImageField(upload_to='players/%m/%d'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='additional_info',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='matches.MatchFixtures')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='players.Players')),
            ],
        ),
    ]
