# Generated by Django 2.2 on 2019-04-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20190411_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='birth_certificate',
            field=models.ImageField(upload_to='birth'),
        ),
        migrations.AlterField(
            model_name='players',
            name='photo',
            field=models.ImageField(upload_to='players'),
        ),
    ]
